routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware'=>['web', 'auth']], function (){
    Route::resource('logs', 'JobLogController')->only(['index', 'show', 'destroy']);
    Route::get('/logs/{type}/{id}', 'JobLogController@showGroup');
    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/watch', 'JobController@watch')->name('jobs.watch');
    Route::get('/job/{job}/show', 'JobController@show')->name('jobs.show');
    Route::get('/job/{job}', 'JobController@create')->name('jobs.create');
    Route::post('/job/{job}', 'JobController@store');
});

app/User.php
<?php

namespace App;

use App\Lib\InteractiveJobs\Models\Job;
use App\Lib\InteractiveJobs\Models\JobLog;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property int    $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 */
class User extends Authenticatable
{
    use Notifiable;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable
        = [
            'name',
            'email',
            'password',
        ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden
        = [
            'password',
            'remember_token',
        ];
    
    public function logs()
    {
        return $this->morphMany(JobLog::class, 'loggable');
    }
    
    public function jobs()
    {
        return $this->hasMany(Job::class, 'created_by');
    }
    
    public function hasJob($jobId):bool
    {
        return $this->jobs()->where('id', $jobId)->exists();
    }
    
    public function isAdmin()
    {
        return $this->name === 'admin';
    }
    
    public function toCredentials()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'role' => $this->isAdmin() ? 'admin' : 'user',
        ];
    }
    
    public function receivesBroadcastNotificationsOn()
    {
        return 'User.' . $this->id;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lastLogs = Auth::user()->logs()->take(5)->latest()->get();
        return view('home', ['logs'=>$lastLogs]);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Lib\InteractiveJobs\Contracts\JobDefinitionRepository;
use App\Lib\InteractiveJobs\Models\Job;
use App\Lib\InteractiveJobs\Models\JobResource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function abort_if;
use function class_basename;
use function compact;
use function redirect;
use function view;

class JobController extends Controller
{
    /**
     * @var \App\Lib\InteractiveJobs\Contracts\JobDefinitionRepository
     */
    protected $repository;
    
    public function __construct(JobDefinitionRepository $repository)
    {
        $this->repository = $repository;
    }
    
    public function index()
    {
        $jobs = Job::query()->latest('created_at')->paginate();
        return view('jobs.index', ['jobs' => $jobs]);
    }
    
    public function watch()
    {
        $jobs = Job::notFinished()->get()->toJson();
        return view('jobs.watch', ['jobs' => $jobs]);
    }
    
    public function create($job)
    {
        $definition = $this->repository->findByName($job);
        abort_if(!$definition, 404);
        return view('jobs.form', ['definition' => $definition]);
    }
    
    public function store(Request $request, $job)
    {
        $definition = $this->repository->findByName($job);
        abort_if(!$definition, 404);
        if (!empty($definition->rules())) {
            $this->validate($request, $definition->rules());
        }
        $jobModel = Job::create([
            'command' => $definition->command(),
            'queue' => $definition->queue(),
            'payload' => $definition->handlePayload($request),
            'created_by' => Auth::user()->id,
        ]);
        return redirect()->route('jobs.show', ['job' => $jobModel]);
    }
    
    public function show(Job $job)
    {
        $definition = $this->repository->findByName(class_basename($job->command));
        $job->setDefinition($definition);
        return view('jobs.show', compact('job', 'definition'));
    }
    
}

app/Http/Controllers/JobLogController.php
<?php

namespace App\Http\Controllers;

use App\Lib\InteractiveJobs\Models\JobLog;
use function redirect;
use function view;

class JobLogController extends Controller
{
    
    public function index()
    {
        $logs = JobLog::groups()->paginate();
        return view('logs.index', ['logs' => $logs]);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Lib\InteractiveJobs\Models\JobLog $log
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(JobLog $log)
    {
        $logs = JobLog::job($log)->paginate();
        return view('logs.show', ['logs' => $logs, 'group' => $log]);
    }
    
    public function showGroup($type, $id)
    {
        $log =  JobLog::where(['loggable_type' => $type, 'loggable_id' => $id])->firstOrFail();
        $logs = JobLog::job($log)->paginate();
        return view('logs.show', ['logs' => $logs, 'group' => $log]);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lib\InteractiveJobs\Models\JobLog $log
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(JobLog $log)
    {
        JobLog::job($log)->delete();
        return redirect()->route('logs.index');
    }
}

resources/views/_menu.blade.php
<div class="card">
    <div class="card-header">Menu</div>
    <div class="list-group list-group-flush">
        <a class="list-group-item list-group-item-action"
           href="/horizon" target="_blank">
            Horizon
        </a>
        <a class="list-group-item list-group-item-action"
           href="{{route('jobs.index')}}">
            Job List
        </a>
        <a class="list-group-item list-group-item-action"
           href="{{route('jobs.watch')}}">
            Active Jobs
        </a>
        <a class="list-group-item list-group-item-action"
           href="{{route('logs.index')}}">
            Logs
        </a>
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-3">
         @include('_menu')
         @include('jobs._menu')
        </div>
        <div class="col-9">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                     @if($logs)
                            <h5>Last logs:</h5>
                        <ul>
                         @foreach($logs as $log)
                                <li>{{$log->created_at}}:  {{$log->message}}</li>
                            @endforeach
                        @endif
                        </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/jobs/_menu.blade.php
@php
    /**
    * @var \App\Lib\InteractiveJobs\JobDefinition[] $definitions
    */
@endphp


<div class="card">
    <div class="card-header">Jobs</div>
    <div class="list-group list-group-flush">
        @foreach($definitions as $definition)
            <a class="list-group-item list-group-item-action @if(Route::input('job') == $definition->name()) active
@endif"
               href="{{route('jobs.create', ['job'=>$definition->name()])}}">
                {{$definition->title()}}
            </a>
        @endforeach
    </div>
</div>

resources/views/jobs/form.blade.php
@php
    /**
    * @var \App\Lib\InteractiveJobs\JobDefinition $definition
    */
@endphp
@extends('jobs.master')
@section('jobs_content')
    <div class="card">
        <div class="card-header">{{$definition->title()}} [{{$definition->name()}}]</div>
        <div class="card-body">
            <form method="post" action="{{route('jobs.create', ['job'=>$definition->name()])}}">
                @csrf
                @if($definition->formView())
                    @include($definition->formView())
                @else
                    @include('jobs.forms.confirm')
                @endif

                <div class="mt-4">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Run it</button>
                    <a href="{{ url()->previous() }}" class="btn btn-sm btn-outline-primary float-right">Go back</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/jobs/forms/confirm.blade.php
<div class="form-group form-check">
    <input type="checkbox" class="form-check-input" name="confirm" id="confirm_field">
    <label class="form-check-label" for="confirm_field">Agree</label>
</div>

resources/views/jobs/forms/dummy.blade.php
<div class="row">
    <div class="col">
        <label for="loop_field">Number of loop iterations</label>
        <input type="number" min="1" max="5" value="3" class="form-control" name="loop" id="loop_field">
    </div>
    <div class="col">
        <label for="delay_field">Delay between iterations in seconds</label>
        <input type="number" min="1" max="5" value="1" class="form-control" name="delay" id="delay_field">
    </div>
</div>

resources/views/jobs/forms/url.blade.php
<div class="form-group form-check">
    <label for="url">Url address</label>
    <input type="url" name="url" value="https://" class="form-control" id="url-field"
           aria-describedby="urlHelp"
           placeholder="https://">
    <small id="urlHelp" class="form-text text-muted">Enter the real url</small>
</div>

resources/views/jobs/index.blade.php
@php
/**
* @var \App\Lib\InteractiveJobs\Models\Job[]|\Illuminate\Support\Collection|\Illuminate\Pagination\LengthAwarePaginator $jobs
**/
@endphp
@extends('jobs.master')
@section('jobs_content')
    <div class="card">
        <div class="card-header">Jobs</div>
        <div class="card-body">
            <table class="table table-sm table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created</th>
                    <th>Finished</th>
                     <th>Owner</th>
                     <th>Queue</th>
                     <th></th>
                </tr>
                </thead>
                @foreach($jobs as $job)
                    <tr>
                        <td>{{$job->id}}</td>
                        <td>{!!$job->jobState()->label()!!} {{$job->command}} </td>
                        <td>{{$job->created_at}}</td>
                        <td>
                            @if($job->finished_at)
                                {{$job->finished_at}}
                            @else
                                @if($job->progress)
                                    {{$job->progress}}%
                                @else
                                    -
                                @endif
                            @endif
                        </td>
                        <td>{{$job->owner->name}}</td>
                        <td>{{$job->queue}}</td>
                        <td>
                            <a href="{{route('jobs.show', ['job'=>$job])}}" class="btn btn-primary">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="card-footer">
            {{$jobs->links()}}
        </div>
    </div>
@endsection

resources/views/jobs/master.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-3">
                @include('_menu')
                @include('jobs._menu')
            </div>
            <div class="col-9">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                @if (session('errors'))
                    <div class="alert alert-danger">
                        {{ session('errors') }}
                    </div>
                @endif
                @yield('jobs_content')
            </div>
        </div>
    </div>
@endsection

resources/views/jobs/show.blade.php
@extends('jobs.master')
@section('jobs_content')
    <active-job job='@json($job)'/>
@endsection

resources/views/jobs/watch.blade.php
@extends('jobs.master')
@section('jobs_content')
    <watch-active list="{{$jobs}}"/>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{config('app.url')}}:6001/socket.io/socket.io.js"></script>
    <script>
        @auth()
        window.appConfig = {
            auth:@json(Auth::user()->toCredentials())
        };
        @elseauth()
            window.appConfig = {
            auth:null
        };
        @endauth
    </script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <script src="https://use.fontawesome.com/cd636b65bd.js"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="{{ asset('js/app.js') }}" defer></script>
</body>
</html>

resources/views/logs/index.blade.php
@php
/**
* @var \Illuminate\Support\Collection|\App\Lib\InteractiveJobs\Models\JobLog[]|\Illuminate\Pagination\LengthAwarePaginator $logs
**/
@endphp
@extends('jobs.master')

@section('jobs_content')
    <div class="card">
        <div class="card-header">Logs</div>
        <div class="card-body">
            <table class="table table-hover table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Job</th>
                    <th scope="col">Records</th>
                    <th scope="col">Last update</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                @forelse ($logs as $log)
                    <tr>
                        <td>{{$log->loggable_type}}:{{$log->loggable_id}}</td>
                        <td>{{$log->total}}</td>
                        <td>{{$log->created_at}}</td>
                        <td ><a class="btn btn-sm btn-primary" href="{{route('logs.show', ['log'=>$log]) }}">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="table-info"> No records</td>
                    </tr>
                @endforelse
            </table>
        </div>
        <div class="card-footer">
            {{$logs->links()}}
        </div>
    </div>
@endsection

resources/views/logs/show.blade.php
@php
    /***
    * @var \App\Lib\InteractiveJobs\Models\JobLog[]|\Illuminate\Pagination\LengthAwarePaginator $logs
    * @var \App\Lib\InteractiveJobs\Models\JobLog $group
    **/
@endphp
@extends('jobs.master')

@section('jobs_content')
    <h4>Logs for {{$group->loggable_type}}: {{$group->loggable_id}}</h4>
    <form action="{{route('logs.destroy', ['log'=>$group])}}"  method="POST">
        @method('DELETE') @csrf
        <button type="submit" class="btn btn-sm btn-danger">
            <i class="fa fa-trash-o"></i> Delete
        </button>
    </form>
    @foreach ($logs as $log)
        <div class="card">
            <div class="card-header">
                <div class="badge badge-info">{{$log->level}}</div>
                <div class="badge badge-dark">{{$log->created_at}}</div>
            </div>
            <div class="card-body">
                {{$log->message}}
                {{$log->context ?? ''}}
                {{$log->extra ?? ''}}
            </div>
        </div>
    @endforeach
    <div>
        {{$logs->links()}}
    </div>
@endsection